version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edith
    ports:
    - "5432:5432"
    volumes:
    - ./postgres_data:/var/lib/postgresql/data

