slack:
  token: xoxb-  # add token
  socket_token: xapp-1- # add socket token
  debug: true

jenkins:
  host: "http://localhost:8080"
  username: shivin  
  password: shivin
  jobs:
    test:
      parameters:
        - name: BRANCH
          default: master
          type: string

crons:
  - schedule: "* 10 * * *"
    channel: "#general"
    commands:
      - weather
      - newsfeed
      - celebrations

open_weather:
  api_key: # open weather api key
  location: Bengaluru

logger:
  level: debug
  file: ./bot.log

timezone: UTC

server:
  base_url: "http://localhost:8000"
  timeout: 10
  max_conns_per_host: 3
