# Generated by Django 3.2.11 on 2022-01-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='edith_models.client'),
        ),
    ]
