# Generated by Django 3.2.11 on 2022-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0010_auto_20220126_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slack_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
