# Generated by Django 3.2.11 on 2022-01-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0003_auto_20220115_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
    ]
