# Generated by Django 3.2.11 on 2022-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0004_auto_20220115_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee', to='edith_models.Skill'),
        ),
    ]
