# Generated by Django 3.2.11 on 2022-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0007_alter_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employee', to='edith_models.Skill'),
        ),
    ]
