# Generated by Django 3.2.11 on 2022-01-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edith_models', '0008_alter_employee_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='type_of_leave',
        ),
    ]
